### PR TITLE
Installing Tensorflow serving from sources

### PR DESCRIPTION
**Pull request by ImenBizid**

### CODE REVIEW

**Comment by andrewssobral** [comment]
@ImenBizid why bug label ?

**Comment by ImenBizid** [comment]
@andrewssobral Tensorflow Serving was not correctly installed in the previous version.

**Comment by andrewssobral** [comment]
this new version is working ? tested?

**Comment by ImenBizid** [comment]
yes. I built the image activeeon/maas_dl:latest and pushed it. You can test it in trydev2.

**Review by andrewssobral — APPROVED** [review]

**Pull request merged**
